int validaCPF(char[]);
int validaEmail(char[]);
int validarNome(char[]);
int validaTelefone(char[]);
int validaID(char[]);
int validaVALOR(float);
int bissexto(int);
int validaData(int, int, int);
int validaConfirmacao(char[]);
void delay(int);
void limpaTela(void);